#pragma once

/**HTTPHeader is used to store information about a HTTPHeader*/
struct HttpHeader{
// int A_IM;
int Accept;
// int Accept_Additions;
// int Accept_CH;
int Accept_Charset;
// int Accept_Datetime;
// int Accept_Encoding;
// int Accept_Features;
// int Accept_Language;
// int Accept_Patch;
// int Accept_Post;
// int Accept_Ranges;
// int Access_Control;
// int Access_Control_Allow_Credentials;
// int Access_Control_Allow_Headers;
// int Access_Control_Allow_Methods;
// int Access_Control_Allow_Origin;
// int Access_Control_Max_Age;
// int Access_Control_Request_Headers;
const char* Access_Control_Request_Method;
// int Age;
// int Allow;
// int ALPN;
// int Alt_Svc;
// int Alt_Used;
// int Alternates;
// int AMP_Cache_Transform;
// int Apply_To_Redirect_Ref;
// int Authentication_Control;
// int Authentication_Info;
// int Authorization;
// int C_Ext;
// int C_Man;
// int C_Opt;
// int C_PEP;
// int C_PEP_Info;
int Cache_Control;
// int Cache_Status;
// int Cal_Managed_ID;
// int CalDAV_Timezones;
// int CDN_Loop;
// int Cert_Not_After;
// int Cert_Not_Before;
// int Close;
// int Compliance;
int Connection;
// int Content_Base;
// int Content_Disposition;
// int Content_Encoding;
int Content_ID;
int Content_Language;
int Content_Length;
// int Content_Location;
// int Content_MD5;
// int Content_Range;
// int Content_Script_Type;
// int Content_Style_Type;
// int Content_Transfer_Encoding;
int Content_Type;
// int Content_Version;
int Cookie;
int Cookie2;
// int Cost;
// int DASL;
int Date;
// int DAV;
// int Default_Style;
// int Delta_Base;
// int Depth;
// int Derived_From;
// int Destination;
// int Differential_ID;
// int Digest;
// int Early_Data;
// int EDIINT_Features;
// int ETag;
int Expect;
// int Expect_CT;
// int Expires;
// int Ext;
int Forwarded;
int From;
// int GetProfile;
// int Hobareg;
int Host;
// int HTTP2_Settings;
// int If;
int If_Match;
int If_Modified_Since;
int If_None_Match;
int If_Range;
// int If_Schedule_Tag_Match;
int If_Unmodified_Since;
// int IM;
// int Include_Referred_Token_Binding_ID;
// int Isolation;
int Keep_Alive;
// int Label;
// int Last_Modified;
// int Link;
// int Location;
// int Lock_Token;
// int Man;;
int Max_Forwards;
// int Memento_Datetime;
// int Message_ID;
// int Meter;
// int Method_Check;
// int Method_Check_Expires;
// int MIME_Version;
// int Negotiate;
// int Non_Compliance;
// int OData_EntityId;
// int OData_Isolation;
// int OData_MaxVersion;
// int OData_Version;
// int Opt;
// int Optional;
// int Optional_WWW_Authenticate;
// int Ordering_Type;
int Origin;
// int OSCORE;
// int OSLC_Core_Version;
// int Overwrite;
// int P3P;
// int PEP;
// int Pep_Info;
// int PICS_Label;
// int Position;
int Pragma;
// int Prefer;
// int Preference_Applied;
// int ProfileObject;
// int Protocol;
// int Protocol_Info;
// int Protocol_Query;
// int Protocol_Request;
// int Proxy_Authenticate;
// int Proxy_Authentication_Info;
int Proxy_Authorization;
// int Proxy_Features;
// int Proxy_Instruction;
// int Proxy_Status;
// int Public;
// int Public_Key_Pins;
// int Public_Key_Pins_Report_Only;
int Range;
// int Redirect_Ref;
int Referer;
// int Referer_Root;
// int Repeatability_Client_ID;
// int Repeatability_First_Sent;
// int Repeatability_Request_ID;
// int Repeatability_Result;
// int Replay_Nonce;
// int Resolution_Hint;
// int Resolver_Location;
// int Retry_After;
// int Safe;
// int Schedule_Reply;
// int Schedule_Tag;
// int Sec_Token_Binding;
// int Sec_WebSocket_Accept;
// int Sec_WebSocket_Extensions;
// int Sec_WebSocket_Key;
// int Sec_WebSocket_Protocol;
// int Sec_WebSocket_Version;
// int Security_Scheme;
// int Server;
// int Set_Cookie;
// int Set_Cookie2;
// int SetProfile;
// int SLUG;
// int SoapAction;
// int Status_URI;
// int Strict_Transport_Security;
// int SubOK;
// int Subst;
// int Sunset;
// int Surrogate_Capability;
// int Surrogate_Control;
// int TCN;
int TE;
// int Timeout;
// int Timing_Allow_Origin;
// int Title;
// int Topic;
// int Traceparent;
// int Tracestate;
// int Trailer;
// int Transfer_Encoding;
// int TTL;
// int UA_Color;
// int UA_Media;
// int UA_Pixels;
// int UA_Resolution;
// int UA_Windowpixels;
int Upgrade;
// int Urgency;
// int URI;
int User_Agent;
// int Variant_Vary;
// int Vary;
// int Version;
int Via;
// int Want_Digest;
int Warning;
// int WWW_Authenticate;
// int X_Content_Type_Options;
// int X_Device_Accept;
// int X_Device_Accept_Charset;
// int X_Device_Accept_Encoding;
// int X_Device_Accept_Language;
// int X_Device_User_Agent;
// int X_Frame_Options;
};
